apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ontap-nas
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "be-volume:.*"
allowVolumeExpansion: true
reclaimPolicy: Delete