---
- hosts: localhost
  name: Create Volume
  vars:
    username: admin
    password: Netapp123456
    aggr: aggr1
    policy: trident
  vars_prompt:
  - name: hostname
    prompt: "What is the cluster admin IP of your CVO?"
    private: no
  - name: vserver
    prompt: "What is the vserver name of your CVO?"
    private: no
  - name: vol_name
    prompt: "What is the volume you want to create?"
    private: no  
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      policy: "{{ policy }}"
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      space_guarantee: none
      volume_security_style: unix
      https: true
      validate_certs: false